movie/app/urls.py
from django.urls import path
from app import views
app_name="app"

urlpatterns = [

    # path('',views.home,name="home"),
    path('',views.Movielist.as_view(),name="home"),

    # path('details/<p>',views.details,name="details"),
    path('movie/<pk>',views.MovieDetail.as_view(),name="details"),

    path('addmovie/',views.Movieadd.as_view(),name="addmovie"),
    # path('update/<p>', views.update, name="update"),
    path('update/<pk>',views.MovieUpdate.as_view(),name='update'),

    # path('delete/<p>', views.delete, name="delete"),
    path('delete/<pk>', views.MovieDelete.as_view(), name="delete"),

]

movie/movie/app/urls.py
from django.urls import path
from app import views
app_name="app"

urlpatterns = [

    # path('',views.home,name="home"),
    path('',views.Movielist.as_view(),name="home"),

    # path('details/<p>',views.details,name="details"),
    path('movie/<pk>',views.MovieDetail.as_view(),name="details"),

    path('addmovie/',views.Movieadd.as_view(),name="addmovie"),
    # path('update/<p>', views.update, name="update"),
    path('update/<pk>',views.MovieUpdate.as_view(),name='update'),

    # path('delete/<p>', views.delete, name="delete"),
    path('delete/<pk>', views.MovieDelete.as_view(), name="delete"),

]

movie/movie/movie/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings


from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movie/movie/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings


from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movie/app/models.py
from django.db import models

class Movie(models.Model):
    name=models.CharField(max_length=20,unique=True,primary_key=True)
    desc=models.TextField()
    year=models.IntegerField()
    image=models.ImageField(upload_to="movies",null=True,blank=True)

    def __str__(self):
        return self.name

movie/movie/app/models.py
from django.db import models

class Movie(models.Model):
    name=models.CharField(max_length=20,unique=True,primary_key=True)
    desc=models.TextField()
    year=models.IntegerField()
    image=models.ImageField(upload_to="movies",null=True,blank=True)

    def __str__(self):
        return self.name

movie/app/forms.py
from django import forms
from app.models import Movie
class movieform(forms.ModelForm):
    class Meta:
        model=Movie
        fields="__all__"

movie/movie/app/forms.py
from django import forms
from app.models import Movie
class movieform(forms.ModelForm):
    class Meta:
        model=Movie
        fields="__all__"

movie/app/views.py
from django.shortcuts import render
from app.models import Movie
from app.forms import movieform
from django.views.generic import ListView, DetailView, CreateView,UpdateView,DeleteView
from django.urls import reverse_lazy
# def home(request):
#     m=Movie.objects.all()
#     return render(request,'home.html',{'m':m})

class Movielist(ListView): #Listview displays all objects/records retriving from a mode.
    model=Movie
    template_name="home.html"
    context_object_name="m"


# def details(request,p):
#     m=Movie.objects.get(name=p)
#     return render(request,'details.html',{'m':m})

class MovieDetail(DetailView):#detailview displays a particular object retrieving from a model.
    model=Movie
    template_name='details.html'
    context_object_name="m"


class Movieadd(CreateView):
    model=Movie
    template_name="addmovie.html"
    fields='__all__'
    success_url=reverse_lazy('app:home')

# def update(request,p):
#     m=Movie.objects.get(name=p)
#     if(request.method=="POST"):
#         form=movieform(request.POST,request.FILES,instance=m)
#         if form.is_valid():
#             form.save()
#             return home(request)
#     form=movieform(instance=m)
#     return render(request,'update.html',{'form':form})

class MovieUpdate(UpdateView):
    model= Movie
    template_name = "update.html"
    fields = '__all__'
    success_url = reverse_lazy('app:home')

# def delete(request,p):
#     m=Movie.objects.get(name=p)
#     m.delete()
#     return home(request)

class MovieDelete(DeleteView):
    model= Movie
    template_name="delete.html"
    success_url = reverse_lazy('app:home')

movie/movie/app/views.py
from django.shortcuts import render
from app.models import Movie
from app.forms import movieform
from django.views.generic import ListView, DetailView, CreateView,UpdateView,DeleteView
from django.urls import reverse_lazy
# def home(request):
#     m=Movie.objects.all()
#     return render(request,'home.html',{'m':m})

class Movielist(ListView): #Listview displays all objects/records retriving from a mode.
    model=Movie
    template_name="home.html"
    context_object_name="m"


# def details(request,p):
#     m=Movie.objects.get(name=p)
#     return render(request,'details.html',{'m':m})

class MovieDetail(DetailView):#detailview displays a particular object retrieving from a model.
    model=Movie
    template_name='details.html'
    context_object_name="m"


class Movieadd(CreateView):
    model=Movie
    template_name="addmovie.html"
    fields='__all__'
    success_url=reverse_lazy('app:home')

# def update(request,p):
#     m=Movie.objects.get(name=p)
#     if(request.method=="POST"):
#         form=movieform(request.POST,request.FILES,instance=m)
#         if form.is_valid():
#             form.save()
#             return home(request)
#     form=movieform(instance=m)
#     return render(request,'update.html',{'form':form})

class MovieUpdate(UpdateView):
    model= Movie
    template_name = "update.html"
    fields = '__all__'
    success_url = reverse_lazy('app:home')

# def delete(request,p):
#     m=Movie.objects.get(name=p)
#     m.delete()
#     return home(request)

class MovieDelete(DeleteView):
    model= Movie
    template_name="delete.html"
    success_url = reverse_lazy('app:home')

movie/movie/templates/addmovie.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form|crispy}}

    <input type="submit">
<!--<h2>Add Movie details</h2>-->
<!--<form method="POST" enctype="multipart/form-data">-->
<!--    {% csrf_token %}-->
<!--    <div class="mb-3">-->
<!--        <label class="form-label">Image</label>-->
<!--        <input type="file" class="form-control" name="i">-->
<!--    </div>-->
<!--    <div class="mb-3">-->
<!--        <label class="form-label">Title</label>-->
<!--        <input type="text" class="form-control" name="t">-->
<!--    </div>-->
<!--    <div class="mb-3">-->
<!--        <label class="form-label">subtitle</label>-->
<!--        <input type="text" class="form-control" name="s">-->
<!--    </div>-->
<!--     <div class="mb-3">-->
<!--        <label class="form-label">year</label>-->
<!--        <input type="number" class="form-control" name="y">-->
<!--     </div>-->
<!--    <div class="mb-3">-->
<!--    <input type="submit" class="form-control btn btn-primary"></input>-->
<!--  </div>-->

<!--</form>-->
{% endblock %}


</body>
</html>

movie/movie/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">ONLINE MOVIE STORE</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

      <form class="d-flex">

        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <a href="{% url 'app:addmovie' %}" class="btn btn-success" style="margin-left:1000px;">ADD MOVIE</a></div>


      </form>
    </div>
  </div>
</nav>
{% block content %}
{% endblock %}
</body>
</html>

movie/movie/templates/delete.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
<center>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <p>Are you sure you want to delete?</p>
        <input type="submit">
    </form>
</center>
{% endblock %}
</body>
</html>

movie/movie/templates/details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="row">

    <div class="col-sm-4">
        <div class="card" style="width: 27rem ">
  <img src="{{m.image.url}}" class="card-img-top" height="200px" width="100%" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{m.name}}</h5>
    <p class="card-text">{{m.desc}}</p>
      <p class="card-text">{{m.year}}</p>
    <a href="{% url 'app:update' m.name %}" class="btn btn-primary">Update</a>
    <a href="{% url 'app:delete' m.name %}" class="btn btn-primary">Delete</a>

  </div>
</div>
</div>
</div>
{% endblock %}

movie/movie/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
<div class="row">
{% for i in m %}
    <div class="col-sm-4">
        <div class="card" style="width: 27rem;">
  <img src="{{i.image.url}}" class="card-img-top" height="200px" width="100%" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.desc}}</p>
          <p class="card-text">{{i.desc}}</p>

    <a href="{%url 'app:details' i.name %}" class="btn btn-primary">Details</a>
  </div>
</div>
</div>
    {% endfor %}
</div>
</div>
{% endblock %}

movie/movie/templates/update.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
<center>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <input type="submit">
    </form>
</center>
{% endblock %}
</body>
</html>

movie/templates/addmovie.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form|crispy}}

    <input type="submit">
<!--<h2>Add Movie details</h2>-->
<!--<form method="POST" enctype="multipart/form-data">-->
<!--    {% csrf_token %}-->
<!--    <div class="mb-3">-->
<!--        <label class="form-label">Image</label>-->
<!--        <input type="file" class="form-control" name="i">-->
<!--    </div>-->
<!--    <div class="mb-3">-->
<!--        <label class="form-label">Title</label>-->
<!--        <input type="text" class="form-control" name="t">-->
<!--    </div>-->
<!--    <div class="mb-3">-->
<!--        <label class="form-label">subtitle</label>-->
<!--        <input type="text" class="form-control" name="s">-->
<!--    </div>-->
<!--     <div class="mb-3">-->
<!--        <label class="form-label">year</label>-->
<!--        <input type="number" class="form-control" name="y">-->
<!--     </div>-->
<!--    <div class="mb-3">-->
<!--    <input type="submit" class="form-control btn btn-primary"></input>-->
<!--  </div>-->

<!--</form>-->
{% endblock %}


</body>
</html>

movie/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">ONLINE MOVIE STORE</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

      <form class="d-flex">

        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <a href="{% url 'app:addmovie' %}" class="btn btn-success" style="margin-left:1000px;">ADD MOVIE</a></div>


      </form>
    </div>
  </div>
</nav>
{% block content %}
{% endblock %}
</body>
</html>

movie/templates/delete.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
<center>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <p>Are you sure you want to delete?</p>
        <input type="submit">
    </form>
</center>
{% endblock %}
</body>
</html>

movie/templates/details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="row">

    <div class="col-sm-4">
        <div class="card" style="width: 27rem ">
  <img src="{{m.image.url}}" class="card-img-top" height="200px" width="100%" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{m.name}}</h5>
    <p class="card-text">{{m.desc}}</p>
      <p class="card-text">{{m.year}}</p>
    <a href="{% url 'app:update' m.name %}" class="btn btn-primary">Update</a>
    <a href="{% url 'app:delete' m.name %}" class="btn btn-primary">Delete</a>

  </div>
</div>
</div>
</div>
{% endblock %}

movie/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
<div class="row">
{% for i in m %}
    <div class="col-sm-4">
        <div class="card" style="width: 27rem;">
  <img src="{{i.image.url}}" class="card-img-top" height="200px" width="100%" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.desc}}</p>
          <p class="card-text">{{i.desc}}</p>

    <a href="{%url 'app:details' i.name %}" class="btn btn-primary">Details</a>
  </div>
</div>
</div>
    {% endfor %}
</div>
</div>
{% endblock %}

movie/templates/update.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
<center>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <input type="submit">
    </form>
</center>
{% endblock %}
</body>
</html>